### PR TITLE
more indent css classes

### PR DESCRIPTION
**Pull request by filonb**

### CODE REVIEW

**Comment by solin** [comment]
Bartek, will you be able to handle 2 and 4 indents?

**Comment by filonb** [comment]
You mean 4-space tabs? As far as I know, we're using 2-space tabs everywhere so that's the only supported style right now.

**Comment by solin** [comment]
I think we can do 2 or 4 indents everywhete. Even 6 and 8 I think.

**Comment by filonb** [comment]
I just checked again, and even though the editor is always set to 2-space tabs, programs can even have 10-space indents and still work.
That's a problem. There is no way to determine if given 10 spaces are 5 indents or 1 indent without any information from other lines. 

So no, this addon cannot handle that. It assumes that indents are 1 tab deep.

**Comment by filonb** [comment]
I might actually be able to handle variable sized indents while still using the addon approach. I'll see what I can do.

**Comment by solin** [comment]
Hm, lets still think about it. If we cannot handle 4 indents and higher, we
would have to prohibit them which would be bad.

**Pull request merged**
